[package]
name = "day19"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }
pathfinding = "4.12.0"

[dev-dependencies]
criterion = { workspace = true }
rstest = { workspace = true }

[[bench]]
name = "criterion"
harness = false
